language: python

sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install coverage
  - pip install codecov

script:
  - python cythonize_numerics.py build_ext --inplace
  - python -m spacy download en
  - coverage run -m pytest test.py
  - coverage report -m

after_success:
  - codecov
